# Generated by Django 5.1.2 on 2024-10-17 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comments_fecha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='Comentario',
        ),
    ]
